language: cpp
dist: trusty
sudo: required

compiler:  
    - gcc


notifications:
  email:
    recipients:
      - juandausa@gmail.com
      - zebas.graffe@gmail.com
      - jasminasf@gmail.com
    on_success: change
    on_failure: always
    
before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -qq
    - if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq libstdc++-4.9-dev; fi
    - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
    - sudo apt-get install -qq libyajl-dev libxml2-dev libxqilla-dev lcov build-essential zlib1g-dev libbz2-dev libsnappy-dev libgtest-dev valgrind
    - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
    - mkdir dependencies
    - cd dependencies
    - wget https://github.com/google/glog/archive/v0.3.4.tar.gz
    - tar xf v0.3.4.tar.gz
    - cd glog-0.3.4
    - ./configure
    - make
    - sudo make install
    - sudo ldconfig -v
    - cd ..
    - wget https://github.com/schuhschuh/gflags/archive/v2.1.2.tar.gz
    - tar xf v2.1.2.tar.gz
    - cd gflags-2.1.2/
    - cmake .
    - make
    - sudo make install
    - sudo ldconfig -v
    - cd ..
    - wget https://github.com/facebook/rocksdb/archive/rocksdb-4.3.1.tar.gz
    - tar xf rocksdb-4.3.1.tar.gz
    - cd rocksdb-rocksdb-4.3.1/
    - make static_lib
    - sudo make install
    - sudo ldconfig -v
    - cd ..
    - ls
    - cd ../AppServer/curl-7.48.0
    - ./configure
    - make
    - sudo make install
    - cd ..
    - cd ..
    - cd ..
    - sudo rm -r dependencies
    
before_script:
    - cd AppServer
    - ./cpplint/cpplint.py --extensions=cpp --linelength=140 ./ar/fi/uba/tallerii/src/*
    - ./cpplint/cpplint.py --extensions=cpp --linelength=140 ./ar/fi/uba/tallerii/main/*
    - cmake .
    - make
    - ./ar/fi/uba/tallerii/test/runTests

script: valgrind --leak-check=full --error-exitcode=1 ./ar/fi/uba/tallerii/test/runTests

after_success: 
    - lcov --capture --directory ./ar/fi/uba/tallerii/test/ --output-file coverageTinderTests.info
    - genhtml coverageTinderTests.info --output-directory coverageHtml
