language: node_js

node_js:
  - "0.10"

sudo: required

notifications:
  email:
    recipients:
      - juandausa@gmail.com
      - zebas.graffe@gmail.com
    on_success: change
    on_failure: always
    
services:
  - postgresql

addons:
  postgresql: "9.3"

install:
  - sudo npm install
  - psql -c 'create database users;' -U postgres
  - psql -f SQL\ Scripts/create_table.sql -d users -U postgres 

# script: 
#  - sudo npm test
